// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { CityDB } from '../city-db'
import { CityService } from '../city.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-city-sorting',
  templateUrl: './city-sorting.component.html',
  styleUrls: ['./city-sorting.component.css']
})
export class CitySortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of City instances that are in the association
  associatedCitys = new Array<CityDB>();

  constructor(
    private cityService: CityService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of city instances
    public dialogRef: MatDialogRef<CitySortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getCitys()
  }

  getCitys(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let city of this.frontRepo.Citys_array) {
          let ID = this.dialogData.ID
          let revPointerID = city[this.dialogData.ReversePointer as keyof CityDB] as unknown as NullInt64
          let revPointerID_Index = city[this.dialogData.ReversePointer + "_Index" as keyof CityDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedCitys.push(city)
          }
        }

        // sort associated city according to order
        this.associatedCitys.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedCitys, event.previousIndex, event.currentIndex);

    // set the order of City instances
    let index = 0

    for (let city of this.associatedCitys) {
      let revPointerID_Index = city[this.dialogData.ReversePointer + "_Index" as keyof CityDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedCitys.forEach(
      city => {
        this.cityService.updateCity(city)
          .subscribe(city => {
            this.cityService.CityServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
