// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { CountryDB } from '../country-db'
import { CountryService } from '../country.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-countrystable',
  templateUrl: './countrys-table.component.html',
  styleUrls: ['./countrys-table.component.css'],
})
export class CountrysTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Country instances
  selection: SelectionModel<CountryDB> = new (SelectionModel)
  initialSelection = new Array<CountryDB>()

  // the data source for the table
  countrys: CountryDB[] = []
  matTableDataSource: MatTableDataSource<CountryDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.countrys
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (countryDB: CountryDB, property: string) => {
      switch (property) {
        case 'ID':
          return countryDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return countryDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (countryDB: CountryDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the countryDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += countryDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private countryService: CountryService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of country instances
    public dialogRef: MatDialogRef<CountrysTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.countryService.CountryServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getCountrys()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<CountryDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getCountrys()
    this.matTableDataSource = new MatTableDataSource(this.countrys)
  }

  getCountrys(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.countrys = this.frontRepo.Countrys_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let country of this.countrys) {
            let ID = this.dialogData.ID
            let revPointer = country[this.dialogData.ReversePointer as keyof CountryDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(country)
            }
            this.selection = new SelectionModel<CountryDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountryDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as CountryDB[]
          for (let associationInstance of sourceField) {
            let country = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountryDB
            this.initialSelection.push(country)
          }

          this.selection = new SelectionModel<CountryDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.countrys
      }
    )
  }

  // newCountry initiate a new country
  // create a new Country objet
  newCountry() {
  }

  deleteCountry(countryID: number, country: CountryDB) {
    // list of countrys is truncated of country before the delete
    this.countrys = this.countrys.filter(h => h !== country);

    this.countryService.deleteCountry(countryID).subscribe(
      country => {
        this.countryService.CountryServiceChanged.next("delete")
      }
    );
  }

  editCountry(countryID: number, country: CountryDB) {

  }

  // display country in router
  displayCountryInRouter(countryID: number) {
    this.router.navigate(["gongtenk_go-" + "country-display", countryID])
  }

  // set editor outlet
  setEditorRouterOutlet(countryID: number) {
    this.router.navigate([{
      outlets: {
        gongtenk_go_editor: ["gongtenk_go-" + "country-detail", countryID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(countryID: number) {
    this.router.navigate([{
      outlets: {
        gongtenk_go_presentation: ["gongtenk_go-" + "country-presentation", countryID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.countrys.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.countrys.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<CountryDB>()

      // reset all initial selection of country that belong to country
      for (let country of this.initialSelection) {
        let index = country[this.dialogData.ReversePointer as keyof CountryDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(country)

      }

      // from selection, set country that belong to country
      for (let country of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = country[this.dialogData.ReversePointer as keyof CountryDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(country)
      }


      // update all country (only update selection & initial selection)
      for (let country of toUpdate) {
        this.countryService.updateCountry(country)
          .subscribe(country => {
            this.countryService.CountryServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountryDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedCountry = new Set<number>()
      for (let country of this.initialSelection) {
        if (this.selection.selected.includes(country)) {
          // console.log("country " + country.Name + " is still selected")
        } else {
          console.log("country " + country.Name + " has been unselected")
          unselectedCountry.add(country.ID)
          console.log("is unselected " + unselectedCountry.has(country.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let country = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountryDB
      if (unselectedCountry.has(country.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<CountryDB>) = new Array<CountryDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          country => {
            if (!this.initialSelection.includes(country)) {
              // console.log("country " + country.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + country.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = country.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = country.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("country " + country.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<CountryDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
