// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { CountryDB } from '../country-db'
import { CountryService } from '../country.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-country-sorting',
  templateUrl: './country-sorting.component.html',
  styleUrls: ['./country-sorting.component.css']
})
export class CountrySortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Country instances that are in the association
  associatedCountrys = new Array<CountryDB>();

  constructor(
    private countryService: CountryService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of country instances
    public dialogRef: MatDialogRef<CountrySortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getCountrys()
  }

  getCountrys(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let country of this.frontRepo.Countrys_array) {
          let ID = this.dialogData.ID
          let revPointerID = country[this.dialogData.ReversePointer as keyof CountryDB] as unknown as NullInt64
          let revPointerID_Index = country[this.dialogData.ReversePointer + "_Index" as keyof CountryDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedCountrys.push(country)
          }
        }

        // sort associated country according to order
        this.associatedCountrys.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedCountrys, event.previousIndex, event.currentIndex);

    // set the order of Country instances
    let index = 0

    for (let country of this.associatedCountrys) {
      let revPointerID_Index = country[this.dialogData.ReversePointer + "_Index" as keyof CountryDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedCountrys.forEach(
      country => {
        this.countryService.updateCountry(country)
          .subscribe(country => {
            this.countryService.CountryServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
