// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { IndividualDB } from '../individual-db'
import { IndividualService } from '../individual.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-individual-sorting',
  templateUrl: './individual-sorting.component.html',
  styleUrls: ['./individual-sorting.component.css']
})
export class IndividualSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Individual instances that are in the association
  associatedIndividuals = new Array<IndividualDB>();

  constructor(
    private individualService: IndividualService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of individual instances
    public dialogRef: MatDialogRef<IndividualSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getIndividuals()
  }

  getIndividuals(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let individual of this.frontRepo.Individuals_array) {
          let ID = this.dialogData.ID
          let revPointerID = individual[this.dialogData.ReversePointer as keyof IndividualDB] as unknown as NullInt64
          let revPointerID_Index = individual[this.dialogData.ReversePointer + "_Index" as keyof IndividualDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedIndividuals.push(individual)
          }
        }

        // sort associated individual according to order
        this.associatedIndividuals.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedIndividuals, event.previousIndex, event.currentIndex);

    // set the order of Individual instances
    let index = 0

    for (let individual of this.associatedIndividuals) {
      let revPointerID_Index = individual[this.dialogData.ReversePointer + "_Index" as keyof IndividualDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedIndividuals.forEach(
      individual => {
        this.individualService.updateIndividual(individual)
          .subscribe(individual => {
            this.individualService.IndividualServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
