// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ConfigurationDB } from '../configuration-db'
import { ConfigurationService } from '../configuration.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-configurationstable',
  templateUrl: './configurations-table.component.html',
  styleUrls: ['./configurations-table.component.css'],
})
export class ConfigurationsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Configuration instances
  selection: SelectionModel<ConfigurationDB> = new (SelectionModel)
  initialSelection = new Array<ConfigurationDB>()

  // the data source for the table
  configurations: ConfigurationDB[] = []
  matTableDataSource: MatTableDataSource<ConfigurationDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.configurations
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (configurationDB: ConfigurationDB, property: string) => {
      switch (property) {
        case 'ID':
          return configurationDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return configurationDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (configurationDB: ConfigurationDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the configurationDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += configurationDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private configurationService: ConfigurationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of configuration instances
    public dialogRef: MatDialogRef<ConfigurationsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.configurationService.ConfigurationServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getConfigurations()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<ConfigurationDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getConfigurations()
    this.matTableDataSource = new MatTableDataSource(this.configurations)
  }

  getConfigurations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.configurations = this.frontRepo.Configurations_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let configuration of this.configurations) {
            let ID = this.dialogData.ID
            let revPointer = configuration[this.dialogData.ReversePointer as keyof ConfigurationDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(configuration)
            }
            this.selection = new SelectionModel<ConfigurationDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ConfigurationDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ConfigurationDB[]
          for (let associationInstance of sourceField) {
            let configuration = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ConfigurationDB
            this.initialSelection.push(configuration)
          }

          this.selection = new SelectionModel<ConfigurationDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.configurations
      }
    )
  }

  // newConfiguration initiate a new configuration
  // create a new Configuration objet
  newConfiguration() {
  }

  deleteConfiguration(configurationID: number, configuration: ConfigurationDB) {
    // list of configurations is truncated of configuration before the delete
    this.configurations = this.configurations.filter(h => h !== configuration);

    this.configurationService.deleteConfiguration(configurationID).subscribe(
      configuration => {
        this.configurationService.ConfigurationServiceChanged.next("delete")
      }
    );
  }

  editConfiguration(configurationID: number, configuration: ConfigurationDB) {

  }

  // display configuration in router
  displayConfigurationInRouter(configurationID: number) {
    this.router.navigate(["gongtenk_go-" + "configuration-display", configurationID])
  }

  // set editor outlet
  setEditorRouterOutlet(configurationID: number) {
    this.router.navigate([{
      outlets: {
        gongtenk_go_editor: ["gongtenk_go-" + "configuration-detail", configurationID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(configurationID: number) {
    this.router.navigate([{
      outlets: {
        gongtenk_go_presentation: ["gongtenk_go-" + "configuration-presentation", configurationID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.configurations.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.configurations.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ConfigurationDB>()

      // reset all initial selection of configuration that belong to configuration
      for (let configuration of this.initialSelection) {
        let index = configuration[this.dialogData.ReversePointer as keyof ConfigurationDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(configuration)

      }

      // from selection, set configuration that belong to configuration
      for (let configuration of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = configuration[this.dialogData.ReversePointer as keyof ConfigurationDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(configuration)
      }


      // update all configuration (only update selection & initial selection)
      for (let configuration of toUpdate) {
        this.configurationService.updateConfiguration(configuration)
          .subscribe(configuration => {
            this.configurationService.ConfigurationServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ConfigurationDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedConfiguration = new Set<number>()
      for (let configuration of this.initialSelection) {
        if (this.selection.selected.includes(configuration)) {
          // console.log("configuration " + configuration.Name + " is still selected")
        } else {
          console.log("configuration " + configuration.Name + " has been unselected")
          unselectedConfiguration.add(configuration.ID)
          console.log("is unselected " + unselectedConfiguration.has(configuration.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let configuration = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ConfigurationDB
      if (unselectedConfiguration.has(configuration.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ConfigurationDB>) = new Array<ConfigurationDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          configuration => {
            if (!this.initialSelection.includes(configuration)) {
              // console.log("configuration " + configuration.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + configuration.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = configuration.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = configuration.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("configuration " + configuration.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ConfigurationDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
