// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CountryDB } from './country-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CountryServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private countrysUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.countrysUrl = origin + '/api/github.com/thomaspeugeot/gongtenk/go/v1/countrys';
  }

  /** GET countrys from the server */
  getCountrys(): Observable<CountryDB[]> {
    return this.http.get<CountryDB[]>(this.countrysUrl)
      .pipe(
        tap(_ => this.log('fetched countrys')),
        catchError(this.handleError<CountryDB[]>('getCountrys', []))
      );
  }

  /** GET country by id. Will 404 if id not found */
  getCountry(id: number): Observable<CountryDB> {
    const url = `${this.countrysUrl}/${id}`;
    return this.http.get<CountryDB>(url).pipe(
      tap(_ => this.log(`fetched country id=${id}`)),
      catchError(this.handleError<CountryDB>(`getCountry id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new country to the server */
  postCountry(countrydb: CountryDB): Observable<CountryDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<CountryDB>(this.countrysUrl, countrydb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryDB>('postCountry'))
    );
  }

  /** DELETE: delete the countrydb from the server */
  deleteCountry(countrydb: CountryDB | number): Observable<CountryDB> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;

    return this.http.delete<CountryDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted countrydb id=${id}`)),
      catchError(this.handleError<CountryDB>('deleteCountry'))
    );
  }

  /** PUT: update the countrydb on the server */
  updateCountry(countrydb: CountryDB): Observable<CountryDB> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<CountryDB>(url, countrydb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryDB>('updateCountry'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
